    drop table FACILITY if exists;

    drop table GOLFER if exists;

    drop table HOLE if exists;

    drop table MEMBER if exists;

    drop table MEMBER_ROLE if exists;

    drop table ROLE if exists;

    drop table ROUND if exists;

    drop table TEE if exists;

    drop table TEE_SET if exists;

    create table COURSE (
        ID bigint generated by default as identity unique,
        DESCRIPTION varchar(255),
        DESIGNER varchar(50),
        FAIRWAYS varchar(15) not null,
        GREENS varchar(15) not null,
        NAME varchar(50),
        NUM_HOLES integer not null,
        SIGNATURE_HOLE bigint,
        YEAR_BUILT integer,
        FACILITY_ID bigint not null,
        primary key (ID)
    );

    create table COURSE_COMMENT (
        id bigint generated by default as identity,
        DATE_POSTED timestamp not null,
        text clob,
        version integer,
        COURSE_ID bigint not null,
        GOLFER_ID bigint not null,
        primary key (id)
    );

    create table FACILITY (
        ID bigint generated by default as identity unique,
        ADDRESS varchar(50),
        CITY varchar(30),
        COUNTRY varchar(30),
        COUNTY varchar(30),
        DESCRIPTION varchar(255),
        NAME varchar(50) not null,
        PHONE varchar(10),
        PRICE_RANGE integer,
        STATE varchar(2),
        TYPE varchar(15) not null,
        URI varchar(255),
        ZIP varchar(5),
        OWNER_ID bigint,
        primary key (ID)
    );

    create table GOLFER (
        joined timestamp not null,
        dob date,
        first_name varchar(255) not null,
        gender varchar(255),
        last_name varchar(255) not null,
        location varchar(255),
        pro_status varchar(255),
        specialty varchar(255),
        MEMBER_ID bigint not null,
        primary key (MEMBER_ID)
    );

    create table HOLE (
        ID bigint generated by default as identity unique,
        L_HANDICAP integer,
        L_PAR integer not null,
        M_HANDICAP integer,
        M_PAR integer not null,
        NAME varchar(25),
        NUMBER integer not null,
        COURSE_ID bigint not null,
        primary key (ID),
        unique (NUMBER, COURSE_ID)
    );

    create table MEMBER (
        id bigint generated by default as identity,
        email_address varchar(255) not null,
        password_hash varchar(255) not null,
        username varchar(255) not null,
        primary key (id),
        unique (email_address),
        unique (username)
    );

    create table MEMBER_ROLE (
        member_id bigint not null,
        role_id bigint not null,
        primary key (member_id, role_id)
    );

    create table ROLE (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id),
        unique (name)
    );

    create table ROUND (
        id bigint generated by default as identity,
        date date,
        notes clob,
        TOTAL_SCORE integer,
        version integer,
        weather varchar(255),
        GOLFER_ID bigint not null,
        TEE_SET_ID bigint not null,
        primary key (id)
    );

    create table TEE (
        HOLE_ID bigint not null,
        TEE_SET_ID bigint not null,
        DISTANCE integer not null,
        primary key (HOLE_ID, TEE_SET_ID)
    );

    create table TEE_SET (
        ID bigint generated by default as identity unique,
        COLOR varchar(10) not null,
        L_COURSE_RATING double,
        L_SLOPE_RATING double,
        M_COURSE_RATING double,
        M_SLOPE_RATING double,
        NAME varchar(25),
        POS integer,
        COURSE_ID bigint not null,
        primary key (ID),
        unique (COLOR, COURSE_ID),
        unique (POS, COURSE_ID)
    );

    alter table COURSE
        add constraint FK76D5D41BF00CEE32
        foreign key (FACILITY_ID)
        references FACILITY;

    alter table COURSE_COMMENT
        add constraint FK10FAAA1B73920CB2
        foreign key (GOLFER_ID)
        references GOLFER;

    alter table COURSE_COMMENT
        add constraint FK10FAAA1BD02D132
        foreign key (COURSE_ID)
        references COURSE;

    alter table FACILITY
        add constraint FK4C845EA31F94B40E
        foreign key (OWNER_ID)
        references GOLFER;

    alter table GOLFER
        add constraint FK7DA4F08F16244CD2
        foreign key (MEMBER_ID)
        references MEMBER;

    alter table HOLE
        add constraint FK21ECC0D02D132
        foreign key (COURSE_ID)
        references COURSE;

    alter table MEMBER_ROLE
        add constraint FKD494C2FB16244CD2
        foreign key (member_id)
        references MEMBER;

    alter table MEMBER_ROLE
        add constraint FKD494C2FBBC4EA552
        foreign key (role_id)
        references ROLE;

    alter table ROUND
        add constraint FK4A8B96E69A235A9
        foreign key (TEE_SET_ID)
        references TEE_SET;

    alter table ROUND
        add constraint FK4A8B96E73920CB2
        foreign key (GOLFER_ID)
        references GOLFER;

    alter table TEE
        add constraint FK143F469A235A9
        foreign key (TEE_SET_ID)
        references TEE_SET;

    alter table TEE
        add constraint FK143F4AB4BC912
        foreign key (HOLE_ID)
        references HOLE;

    alter table TEE_SET
        add constraint FKD5429977D02D132
        foreign key (COURSE_ID)
        references COURSE;
