DROP TABLE IF EXISTS PUBLIC.GOLFER;
DROP TABLE IF EXISTS PUBLIC.MEMBER;

CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_MEMBER START WITH 1 BELONGS_TO_TABLE;

CREATE CACHED TABLE PUBLIC.MEMBER(
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_MEMBER) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_MEMBER,
    USERNAME VARCHAR(255),
    PASSWORD_HASH VARCHAR(255),
    EMAIL_ADDRESS VARCHAR(255)
);
CREATE PRIMARY KEY ON PUBLIC.MEMBER(ID);

CREATE CACHED TABLE PUBLIC.GOLFER(
    MEMBER_ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(255),
    GENDER VARCHAR(255),
    JOINED TIMESTAMP NOT NULL,
    DOB DATE,
    SPECIALTY VARCHAR(255),
    PRO_STATUS VARCHAR(255)
);
CREATE PRIMARY KEY ON PUBLIC.GOLFER(MEMBER_ID);

ALTER TABLE PUBLIC.GOLFER ADD CONSTRAINT PUBLIC.FK_GOLFER_REF_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES PUBLIC.MEMBER(ID);
ALTER TABLE PUBLIC.MEMBER ADD CONSTRAINT PUBLIC.UNIQ_USERNAME UNIQUE(USERNAME);
ALTER TABLE PUBLIC.MEMBER ADD CONSTRAINT PUBLIC.UNIQ_EMAIL_ADDRESS UNIQUE(EMAIL_ADDRESS);
